version: "3.8"
services:
  backend:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    depends_on:
      - neo4j
      - redis
    environment:
      - NEO4J_URI=neo4j://neo4j:7474
      - REDIS_HOST=redis

  frontend:
    build:
      context: ../client
      dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/test

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
