# Specify the node base image with the version as a parameter.
FROM node:20-alpine

# Set the working directory in the container.
WORKDIR /app

# Copy package.json and package-lock.json.
COPY package.json package-lock.json ./

# Install dependencies.
RUN npm install

# Copy the rest of the client application.
COPY . .

# Build the project for production.
RUN npm run build

# Expose the port the app runs on.
EXPOSE 3000

# Command to run the app.
CMD ["npm", "start"]
