// api/model/neo4j/relationships.go
package echo_neo4j

// Relationship Types
const (
	// RelPartOf represents the relationship between a department and its organization
	RelPartOf = "PART_OF"

	// RelChildOf represents the relationship between a department and its parent department
	RelChildOf = "CHILD_OF"

	// RelWorksFor represents the relationship between a user and their organization
	RelWorksFor = "WORKS_FOR"

	// RelMemberOf represents the relationship between a user and their department
	RelMemberOf = "MEMBER_OF"

	// RelHasRole represents the relationship between a user and their assigned roles
	RelHasRole = "HAS_ROLE"

	// RelHasPermission represents the relationship between a role and its permissions
	RelHasPermission = "HAS_PERMISSION"

	// RelOwns represents the relationship between an organization and its resources
	RelOwns = "OWNS"

	// RelCanAccess represents the relationship between a role and the resources it can access
	RelCanAccess = "CAN_ACCESS"

	// RelAppliesTo represents the relationship between a policy and the resources it applies to
	RelAppliesTo = "APPLIES_TO"

	RelHasCondition = "HAS_CONDITION"

	// RelHasAttribute represents the relationship between a node and its attributes
	RelHasAttribute = "HAS_ATTRIBUTE"

	// RelBelongsToGroup represents the relationship between a user and their groups
	RelBelongsToGroup = "BELONGS_TO_GROUP"

	// RelHasType represents the relationship between a resource and its type
	RelHasType = "HAS_TYPE"
	// RelCreatedBy represents the relationship between a node and its creator
	RelCreatedBy = "CREATED_BY"

	// RelUpdatedBy represents the relationship between a node and its last updater
	RelUpdatedBy = "UPDATED_BY"

	// RelBelongsToOrg represents the relationship between a user and their organization
	RelBelongsToOrg = "BELONGS_TO_ORG"

	// RelRelatedTo represents the relationship between resource and related to resource
	RelRelatedTo = "RELATED_TO"

	// RelBelongsToDept represents the relationship between a user and their department
	RelBelongsToDept = "BELONGS_TO_DEPT"

	// RelOwnedBy represents the relationship between a resource and its owner
	RelOwnedBy = "OWNED_BY"

	// RelInAttributeGroup represents the relationship between an resource and its attribute group
	RelInAttributeGroup = "IN_ATTRIBUTE_GROUP"

	// New relationships for resources
	RelDerivedFrom   = "DERIVED_FROM"   // Represents a resource derived from another resource
	RelVersionOf     = "VERSION_OF"     // Represents different versions of a resource
	RelReferencedBy  = "REFERENCED_BY"  // Represents a resource being referenced by another resource
	RelContains      = "CONTAINS"       // Represents a resource containing other resources (e.g., folder containing files)
	RelRequires      = "REQUIRES"       // Represents a resource requiring access to another resource
	RelTaggedWith    = "TAGGED_WITH"    // Represents a resource being tagged with a specific tag
	RelClassifiedAs  = "CLASSIFIED_AS"  // Represents a resource's classification
	RelLocatedIn     = "LOCATED_IN"     // Represents a resource's physical or logical location
	RelManagedBy     = "MANAGED_BY"     // Represents a resource being managed by a specific entity (user, group, or department)
	RelSharedWith    = "SHARED_WITH"    // Represents a resource being shared with a user or group
	RelAccessedBy    = "ACCESSED_BY"    // Represents a resource being accessed by a user (for audit purposes)
	RelModifiedBy    = "MODIFIED_BY"    // Represents a resource being modified by a user (for audit purposes)
	RelApprovedBy    = "APPROVED_BY"    // Represents a resource being approved by a user or group
	RelReviewedBy    = "REVIEWED_BY"    // Represents a resource being reviewed by a user or group
	RelEncryptedWith = "ENCRYPTED_WITH" // Represents a resource being encrypted with a specific key or method
	RelCompiledFrom  = "COMPILED_FROM"  // Represents a compiled resource and its source
	RelLinkedTo      = "LINKED_TO"      // Represents resources that are linked or associated in some way
	RelInheritsFrom  = "INHERITS_FROM"  // Represents inheritance of properties or access rights
	RelSupersedes    = "SUPERSEDES"     // Represents a resource that replaces or supersedes another
	RelHasBackup     = "HAS_BACKUP"     // Represents a resource and its backup
	RelHasMetadata   = "HAS_METADATA"   // Represents a resource and its associated metadata
	RelUsedIn        = "USED_IN"        // Represents a resource being used in a process or another resource
	RelGeneratedBy   = "GENERATED_BY"   // Represents a resource generated by a process or another resource
	RelHasLifecycle  = "HAS_LIFECYCLE"  // Represents a resource's association with a lifecycle stage
	RelCompliesWith  = "COMPLIES_WITH"  // Represents a resource's compliance with a standard or regulation
)
