neo4j:
  uri: "bolt://localhost:7687"
  username: "neo4j"
  password: "Iamhappy@77" # Make sure this matches the password defined in your docker-compose.yml
redis:
  addr: "localhost:6379"
  encryptionKey: "3Rf7h9x1Kp2Lm5Nq8Tw4Yz6Bc0De3Fg1"
log:
  level: "debug"
  format: "text"
  output: "stdout"
  file: "./logging"
rate_limit:
  requests: 10
auth:
  cognito:
    user_pool_id: "ap-south-1_R3kToysyE"
    aws_region: "ap-south-1"
