neo4j:
  uri: "bolt://neo4j:7687"
  username: "neo4j"
  password: "secretpassword" # Make sure this matches the password defined in your docker-compose.yml
redis:
  addr: "redis:6379"
  encryptionKey: "3Rf7h9x1Kp2Lm5Nq8Tw4Yz6Bc0De3Fg1"
log:
  level: "debug"
  format: "text"
  output: "stdout"
  file: "./logging"
logging:
  driver: "json-file"
  options:
    max-size: "200m"
    max-file: "10"
rate_limit:
  requests: 10
auth:
  cognito:
    user_pool_id: "ap-south-1_R3kToysyE"
    aws_region: "ap-south-1"
